# Data Clean up

Haytham Mohamed - INFS890 Spring 2020

This notebook is to check missing data and outliers

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns
from sklearn import preprocessing
from datetime import datetime
from scipy import stats

sns.set()
sns.set(color_codes=True)
#sns.set_color_codes()

pd.options.display.max_rows = 15
pd.options.display.float_format = '{:,.3f}'.format

# Read the raw data. 

All data is in one file, where each metric is listed under each other with three columns: 

1- metric: The name of the metric

2- date: the data and time of the metric

3- value: the metric value

In [24]:
# 1- read data file (from all runs 1 & 2)

file_dir = '/Users/hmohamed/github/data-research-spring2020/raw-data-linode-run3-rules/'
data_file = 'aligned_dataset.csv'

raw_data = pd.read_csv(file_dir + data_file)

raw_data.date = pd.to_datetime(raw_data.date)
raw_data.set_index('date', inplace=True)

raw_data.shape

(4719, 14)

In [25]:
raw_data = raw_data.drop('system_net_sat', 1)
raw_data = raw_data.drop('system_disk_sat', 1)
raw_data = raw_data.drop('system_disk_io', 1)
raw_data = raw_data.drop('system_cpu_sat', 1)

# Check Outliers

In [26]:
raw_data.describe(include="all")

,svc_resp_size,svc_cpu_use,svc_req_rate,system_net_use,svc_pods,svc_net_use,system_cpu_use,svc_ltcy_200,svc_disk_use,svc_req_size
count,"4,719.000","4,719.000","4,719.000","4,719.000","4,719.000","4,719.000","4,719.000","4,719.000","4,719.000","4,719.000"
mean,158.293,4.809,41.606,18.089,16.075,2.607,8.712,6.856,248.703,36.806
std,100.108,13.578,28.226,8.829,10.231,13.648,3.520,4.242,"1,217.339",21.135
min,0.191,-9.299,0.110,2.551,3.000,-12.549,2.770,0.010,-13.022,1.309
25%,84.409,-0.318,20.930,11.702,6.500,-1.592,6.040,1.845,2.188,23.557
50%,151.855,2.719,38.820,17.292,15.000,0.461,7.170,10.000,13.123,34.240
75%,212.920,7.084,54.045,21.667,24.000,3.468,11.420,10.000,56.961,45.838
max,705.249,633.065,196.870,55.856,45.000,511.000,18.260,10.000,"35,499.460",188.819

In [27]:
if 1 == 1: 
    # svc_req_rate
    q = raw_data['svc_req_rate'].quantile(0.90)
    raw_data = raw_data[raw_data['svc_req_rate'] < q]
    
    # svc_req_size
    q = raw_data['svc_req_size'].quantile(0.92)
    raw_data = raw_data[raw_data['svc_req_size'] < q]    
    
    # svc_cpu_use
    q = raw_data['svc_cpu_use'].quantile(0.99)
    raw_data = raw_data[raw_data['svc_cpu_use'] < q]
    
    # svc_net_use
    q = raw_data['svc_net_use'].quantile(0.95)
    raw_data = raw_data[raw_data['svc_net_use'] < q]    
    
    # svc_disk_use
    q = raw_data['svc_disk_use'].quantile(0.70)
    raw_data = raw_data[raw_data['svc_disk_use'] < q]
    
    # svc_resp_size
    q = raw_data['svc_resp_size'].quantile(0.90)
    raw_data = raw_data[raw_data['svc_resp_size'] < q]
    
    #sns.distplot(raw_data['svc_disk_use'])
    
raw_data.shape

(2313, 10)

In [28]:
raw_data.describe(include="all")

,svc_resp_size,svc_cpu_use,svc_req_rate,system_net_use,svc_pods,svc_net_use,system_cpu_use,svc_ltcy_200,svc_disk_use,svc_req_size
count,"2,313.000","2,313.000","2,313.000","2,313.000","2,313.000","2,313.000","2,313.000","2,313.000","2,313.000","2,313.000"
mean,130.197,3.931,33.617,15.824,13.255,0.524,7.602,6.362,5.737,30.517
std,68.142,6.824,17.567,7.010,8.299,3.344,2.756,4.548,8.919,13.244
min,0.614,-9.299,0.110,2.551,3.000,-11.273,2.770,0.010,-12.569,1.922
25%,77.563,-0.626,17.820,10.621,6.500,-1.467,5.910,0.020,-0.960,19.910
50%,139.572,2.297,34.130,15.506,7.000,0.143,6.690,9.920,4.398,32.079
75%,168.183,6.401,49.800,20.702,20.000,2.235,9.120,10.000,11.864,38.615
max,273.684,37.282,73.130,54.049,45.000,12.769,18.110,10.000,27.922,60.309

## Save Dataset to a file

In [29]:
if 1 == 1:
    cleaned_file_path = file_dir + 'no_outliers_dataset.csv'
    raw_data.to_csv(path_or_buf=cleaned_file_path, index=True)